In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

import pandas_market_calendars as mcal

data_folder = './data/'

In [2]:
df = pd.read_csv(data_folder + 'NASDAQ100_m.csv')
df

,Unnamed: 0,ATVI_close,ADBE_close,AMD_close,ALGN_close,ALXN_close,AMZN_close,AMGN_close,AAL_close,ADI_close,...,VRSN_close,VRSK_close,VRTX_close,WBA_close,WDC_close,WDAY_close,WYNN_close,XEL_close,XLNX_close,close
0,2019-07-01 13:31:00+00:00,47.9000,298.140,31.8500,281.9000,131.340,1921.50,185.700,33.3600,117.500,...,212.100,147.460,184.682,55.4900,50.200,209.410,130.52,59.4400,121.6500,7807.485
1,2019-07-01 13:32:00+00:00,47.7625,298.355,31.9500,282.7800,131.300,1923.26,185.763,33.4450,117.000,...,212.660,147.833,183.719,55.5100,50.250,209.480,129.80,59.4300,122.0495,7811.213
2,2019-07-01 13:33:00+00:00,47.8800,298.500,31.6400,282.0400,131.410,1920.76,186.160,33.5551,116.640,...,212.660,147.570,183.175,55.6500,50.210,209.960,130.50,59.4200,122.0000,7807.332
3,2019-07-01 13:34:00+00:00,48.0191,299.400,31.5100,280.7800,131.075,1920.93,186.040,33.5600,116.570,...,212.660,147.635,183.260,55.5900,50.045,209.920,130.45,59.5500,121.6150,7805.444
4,2019-07-01 13:35:00+00:00,47.8900,299.320,31.4500,282.3000,130.735,1920.77,186.030,33.4700,116.640,...,212.625,147.940,183.555,55.5600,50.010,209.454,131.68,59.5450,121.7350,7806.717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52105,2020-01-10 20:56:00+00:00,58.9600,339.980,48.1650,293.1600,109.590,1885.41,238.295,27.3100,118.620,...,209.380,157.435,228.870,54.2492,67.830,180.060,143.13,62.6350,99.5500,8967.428
52106,2020-01-10 20:57:00+00:00,58.9600,340.020,48.1800,293.2800,109.550,1884.45,238.270,27.3250,118.620,...,209.370,157.490,228.910,54.2856,67.900,180.140,143.14,62.6800,99.5550,8969.717
52107,2020-01-10 20:58:00+00:00,58.9600,340.000,48.1900,293.3450,109.520,1883.42,238.310,27.3150,118.560,...,209.240,157.400,228.900,54.3000,67.890,180.160,143.03,62.6550,99.4900,8967.755
52108,2020-01-10 20:59:00+00:00,58.9550,339.905,48.1775,293.3375,109.500,1883.29,238.285,27.3175,118.565,...,209.180,157.360,228.925,54.2600,67.915,180.135,143.02,62.6475,99.4800,8967.196
52109,2020-01-10 21:00:00+00:00,58.9500,339.810,48.1650,293.3300,109.480,1883.16,238.260,27.3200,118.570,...,209.120,157.320,228.950,54.2200,67.940,180.110,143.01,62.6400,99.4700,8966.637

In [9]:
df.replace({-9999: np.nan}, inplace=True)
df['Time'] = df['Time']+'+00:00'
df.interpolate(method='linear',limit_direction='both', inplace=True)
df.set_index('Time', inplace=True)
df.head()

,005930_close,005380_close,000660_close,012330_close,035420_close,005490_close,015760_close,005935_close,000270_close,032830_close,...,004490_close,066575_close,020000_close,082740_close,017800_close,005880_close,017390_close,058650_close,031430_close,close
Time,,,,,,,,,,,,,,,,,,,,,
2019-07-02 00:00:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,42000.000000,32250.000000,36350.0,3885.000000,97000.0,26450.0,78300.0,93200.000000,215500.0,2122.07
2019-07-02 00:01:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,42000.000000,32325.000000,36300.0,3850.000000,97100.0,26550.0,78300.0,93233.333333,215000.0,2119.29
2019-07-02 00:02:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41866.666667,32400.000000,36300.0,3805.000000,96400.0,26450.0,78300.0,93266.666667,215500.0,2117.80
2019-07-02 00:03:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41733.333333,32408.333333,36300.0,3816.666667,96600.0,26400.0,78300.0,93300.000000,214500.0,2117.65
2019-07-02 00:04:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41600.000000,32416.666667,36150.0,3828.333333,97100.0,26250.0,78300.0,93333.333333,213500.0,2115.24

In [10]:
date = mcal.get_calendar('XKRX')

In [11]:
early = date.schedule(start_date='2019-07-02', end_date='2020-01-14')
df.index = pd.to_datetime(df.index)

df = df.resample('1min').first().loc[mcal.date_range(early, frequency='1min')].interpolate(method='linear', limit_direction='both')
df

,005930_close,005380_close,000660_close,012330_close,035420_close,005490_close,015760_close,005935_close,000270_close,032830_close,...,004490_close,066575_close,020000_close,082740_close,017800_close,005880_close,017390_close,058650_close,031430_close,close
2019-07-02 00:01:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,42000.000000,32325.000000,36300.000000,3850.000000,97100.0,26550.000000,78300.000000,93233.333333,215000.000000,2119.29
2019-07-02 00:02:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41866.666667,32400.000000,36300.000000,3805.000000,96400.0,26450.000000,78300.000000,93266.666667,215500.000000,2117.80
2019-07-02 00:03:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41733.333333,32408.333333,36300.000000,3816.666667,96600.0,26400.000000,78300.000000,93300.000000,214500.000000,2117.65
2019-07-02 00:04:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41600.000000,32416.666667,36150.000000,3828.333333,97100.0,26250.000000,78300.000000,93333.333333,213500.000000,2115.24
2019-07-02 00:05:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,41700.000000,32425.000000,36400.000000,3840.000000,96800.0,26200.000000,78300.000000,93366.666667,212500.000000,2113.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-01-14 06:26:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,35763.636364,27700.000000,30636.363636,4742.727273,68900.0,21768.181818,69514.285714,77030.769231,256681.818182,2237.22
2020-01-14 06:27:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,35772.727273,27700.000000,30627.272727,4744.545455,68900.0,21763.636364,69485.714286,77023.076923,256636.363636,2237.22
2020-01-14 06:28:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,35781.818182,27700.000000,30618.181818,4746.363636,68900.0,21759.090909,69457.142857,77015.384615,256590.909091,2237.22
2020-01-14 06:29:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,35790.909091,27700.000000,30609.090909,4748.181818,68900.0,21754.545455,69428.571429,77007.692308,256545.454545,2237.22
2020-01-14 06:30:00+00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,35800.000000,27700.000000,30600.000000,4750.000000,68900.0,21750.000000,69400.000000,77000.000000,256500.000000,2238.88

In [12]:
df.to_csv(data_folder + 'KOSPI200_m.csv')